/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface StencilToDoList {
        "toDoList": any;
        "toDoListId": number;
        "toDoLists": any;
    }
    interface StencilToDoListPreview {
        "toDoList": any;
        "toDoListId": number;
        "toDoLists": any;
    }
    interface StencilToDoLists {
        "toDoLists": any;
    }
}
declare global {
    interface HTMLStencilToDoListElement extends Components.StencilToDoList, HTMLStencilElement {
    }
    var HTMLStencilToDoListElement: {
        prototype: HTMLStencilToDoListElement;
        new (): HTMLStencilToDoListElement;
    };
    interface HTMLStencilToDoListPreviewElement extends Components.StencilToDoListPreview, HTMLStencilElement {
    }
    var HTMLStencilToDoListPreviewElement: {
        prototype: HTMLStencilToDoListPreviewElement;
        new (): HTMLStencilToDoListPreviewElement;
    };
    interface HTMLStencilToDoListsElement extends Components.StencilToDoLists, HTMLStencilElement {
    }
    var HTMLStencilToDoListsElement: {
        prototype: HTMLStencilToDoListsElement;
        new (): HTMLStencilToDoListsElement;
    };
    interface HTMLElementTagNameMap {
        "stencil-to-do-list": HTMLStencilToDoListElement;
        "stencil-to-do-list-preview": HTMLStencilToDoListPreviewElement;
        "stencil-to-do-lists": HTMLStencilToDoListsElement;
    }
}
declare namespace LocalJSX {
    interface StencilToDoList {
        "toDoList"?: any;
        "toDoListId"?: number;
        "toDoLists"?: any;
    }
    interface StencilToDoListPreview {
        "toDoList"?: any;
        "toDoListId"?: number;
        "toDoLists"?: any;
    }
    interface StencilToDoLists {
        "toDoLists"?: any;
    }
    interface IntrinsicElements {
        "stencil-to-do-list": StencilToDoList;
        "stencil-to-do-list-preview": StencilToDoListPreview;
        "stencil-to-do-lists": StencilToDoLists;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "stencil-to-do-list": LocalJSX.StencilToDoList & JSXBase.HTMLAttributes<HTMLStencilToDoListElement>;
            "stencil-to-do-list-preview": LocalJSX.StencilToDoListPreview & JSXBase.HTMLAttributes<HTMLStencilToDoListPreviewElement>;
            "stencil-to-do-lists": LocalJSX.StencilToDoLists & JSXBase.HTMLAttributes<HTMLStencilToDoListsElement>;
        }
    }
}
